{
 "title": "Netology",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "CPULA5",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_load5" }
   ]
  },
  {
   "title": "CPULA15",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_load15" }
   ]
  },
  {
   "title": "CPULA1",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_load1" }
   ]
  },
  {
   "title": "memory MemAvailable bytes",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_memory_MemAvailable_bytes" }
   ]
  },
  {
   "title": "CPU для nodeexporter",
   "type": "stat",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (avg(rate(node_cpu_seconds_total{mode=\"idle\"}[5m])) by (instance) * 100)"
    }
   ]
  },
  {
   "title": "filesystem free bytes",
   "type": "stat",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_free_bytes{fstype!=\"tmpfs\", mountpoint=\"/\"}"
    }
   ]
  }
 ]
}